Android App Version 12 Crash Resolved
java.lang.IllegalArgumentException: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Issue Resolved. Added the flag for sdk versions above 23 which support FLAG_IMMUTABLE and FLAG_MUTABLE. This prevents the app from crashing